In [1]:
import torch
import torch.nn.functional as F 
import matplotlib.pyplot as plt   
%matplotlib inline 

In [2]:
import requests

url = "https://raw.githubusercontent.com/karpathy/makemore/master/names.txt"
response = requests.get(url)
words = response.text.splitlines()

In [3]:
len(words)

32033

In [4]:
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.'] = 0
itos= {i:s for s,i in stoi.items()}
print(itos)

{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f', 7: 'g', 8: 'h', 9: 'i', 10: 'j', 11: 'k', 12: 'l', 13: 'm', 14: 'n', 15: 'o', 16: 'p', 17: 'q', 18: 'r', 19: 's', 20: 't', 21: 'u', 22: 'v', 23: 'w', 24: 'x', 25: 'y', 26: 'z', 0: '.'}


In [8]:
block_size = 3
X, Y = [],[]
for w in words[:2]:
    print(w)
    context = [0]* block_size
    for ch in w +'.':
        ix = stoi[ch]
        X.append(context)
        Y.append(ix)
        print(''.join(itos[i] for i in context), '--->', itos[ix])
        context = context[1:] + [ix] 
X= torch.tensor(X)
Y= torch.tensor(Y)

emma
... ---> e
..e ---> m
.em ---> m
emm ---> a
mma ---> .
olivia
... ---> o
..o ---> l
.ol ---> i
oli ---> v
liv ---> i
ivi ---> a
via ---> .


In [19]:
print(X.shape)
X

torch.Size([12, 3])


tensor([[ 0,  0,  0],
        [ 0,  0,  5],
        [ 0,  5, 13],
        [ 5, 13, 13],
        [13, 13,  1],
        [ 0,  0,  0],
        [ 0,  0, 15],
        [ 0, 15, 12],
        [15, 12,  9],
        [12,  9, 22],
        [ 9, 22,  9],
        [22,  9,  1]])

In [22]:
X[4,2]

tensor(1)

In [29]:
print(C.shape,C)

torch.Size([27, 2]) tensor([[0.2077, 0.3246],
        [0.9978, 0.8813],
        [0.5620, 0.8302],
        [0.6073, 0.0838],
        [0.7588, 0.2460],
        [0.6222, 0.0535],
        [0.3003, 0.3662],
        [0.1169, 0.1318],
        [0.9383, 0.1928],
        [0.5196, 0.1166],
        [0.8936, 0.7688],
        [0.4461, 0.9003],
        [0.8967, 0.6886],
        [0.9092, 0.6875],
        [0.2514, 0.3739],
        [0.5635, 0.9006],
        [0.0727, 0.8799],
        [0.8660, 0.3572],
        [0.2903, 0.2857],
        [0.7972, 0.1187],
        [0.2219, 0.2163],
        [0.4515, 0.1354],
        [0.0872, 0.6617],
        [0.9519, 0.3347],
        [0.2342, 0.9339],
        [0.2826, 0.5117],
        [0.7038, 0.8088]])


In [37]:
print(C[X].shape,C[X])

torch.Size([12, 3, 2]) tensor([[[0.5852, 0.3328],
         [0.5852, 0.3328],
         [0.5852, 0.3328]],

        [[0.5852, 0.3328],
         [0.5852, 0.3328],
         [0.5436, 0.0845]],

        [[0.5852, 0.3328],
         [0.5436, 0.0845],
         [0.7606, 0.8686]],

        [[0.5436, 0.0845],
         [0.7606, 0.8686],
         [0.7606, 0.8686]],

        [[0.7606, 0.8686],
         [0.7606, 0.8686],
         [0.2571, 0.9054]],

        [[0.5852, 0.3328],
         [0.5852, 0.3328],
         [0.5852, 0.3328]],

        [[0.5852, 0.3328],
         [0.5852, 0.3328],
         [0.0248, 0.2892]],

        [[0.5852, 0.3328],
         [0.0248, 0.2892],
         [0.7736, 0.7344]],

        [[0.0248, 0.2892],
         [0.7736, 0.7344],
         [0.7935, 0.8324]],

        [[0.7736, 0.7344],
         [0.7935, 0.8324],
         [0.3800, 0.9211]],

        [[0.7935, 0.8324],
         [0.3800, 0.9211],
         [0.7935, 0.8324]],

        [[0.3800, 0.9211],
         [0.7935, 0.8324],
         [

In [23]:
C[X][4,2]

tensor([0.9978, 0.8813])

In [36]:
C=torch.rand((27,2))

In [ ]:
#So from here we can see that pytorch has created an embedding where X, in which 
# each value corresponds to an index which is being used to call the embedding 
# space which is a 2 dimensional array.
#being used to 
emb= C[X]
emb.shape

torch.Size([12, 3, 2])

In [40]:
W1 = torch.randn((6,100))
b1 = torch.rand(100)

In [41]:
emb @ W1 + b

RuntimeError: mat1 and mat2 shapes cannot be multiplied (36x2 and 6x100)

In [ ]:
# this is much more ineffecient 

#torch.cat(torch.unbind(emb,1),1).shape

torch.Size([12, 6])

In [44]:
a= torch.arange(18)
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [45]:
a.view(6,3)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])

In [47]:
h= emb.view(12,6) @ W1 +b1

In [49]:
h.shape

torch.Size([12, 100])

In [50]:
W2 = torch.rand((100,27))
b2 = torch.randn(27)

In [51]:
logits = h @ W2 + b2

In [54]:
counts= logits.exp()
prob = counts / counts.sum(1, keepdims = True)

In [60]:
prob.shape

torch.Size([12, 27])

In [58]:
loss= -prob[torch.arange(12),Y].log().mean()

loss

tensor(12.4445)

In [ ]:
#The forward pass and backward pass in this case is much more well behaved and much more efficient
#as there is no need for any intermediate tensors for it to work.
#
F.cross_entropy(logits,Y)

tensor(12.4445)

In [167]:
g=torch.Generator().manual_seed(14526)

block_size = 3
X, Y = [],[]
for w in words[:]:
    #print(w)
    context = [0]* block_size
    for ch in w +'.':
        ix = stoi[ch]
        X.append(context)
        Y.append(ix)
        #print(''.join(itos[i] for i in context), '--->', itos[ix])
        context = context[1:] + [ix] 
X= torch.tensor(X)
Y= torch.tensor(Y)


In [168]:
g=torch.Generator().manual_seed(2147483647)
W1 = torch.randn((6,100), requires_grad= True, generator=g)
b1 = torch.randn(100, requires_grad=True, generator=g)
W2 = torch.randn((100,27), requires_grad= True, generator=g)
b2 = torch.randn((27), requires_grad= True, generator=g)
C=torch.randn((27,2), requires_grad= True, generator=g)
parameters=[C,W1,b1,W2,b2]

In [169]:
emb= C[X]
emb.shape


torch.Size([228146, 3, 2])

In [170]:
for _ in range(100):
    # forward
    h = emb.view(228146, 6) @ W1 + b1
    logits = h @ W2 + b2
    loss = F.cross_entropy(logits, Y)

    # backward
    loss.backward()

    
    
    for p in parameters:
        p -= 0.1 * p.grad   # ✅ this works ONLY inside no_grad
    
    print(loss.item())
    # clear grads for next step
    for p in parameters:
        p.grad = None   # ✅ modern way (same as zero_())

    print(loss.item())


RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.

In [ ]:
F.one_hot(5,num_classes=27)